### ISSUE TITLE
wouldnt be able to start here is the log.

### ISSUE THREAD

**Issue by aalpgiray** [rackt/example-react-router-server-rendering-lazy-routes#13]
0 info it worked if it ends with ok
1 verbose cli [ 'B:\node\node.exe',
1 verbose cli   'B:\node\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-router-lazy-route-server-rendering@1.0.0
6 info start react-router-lazy-route-server-rendering@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-router-lazy-route-server-rendering@1.0.0 Failed to exec start script
9 verbose stack Error: react-router-lazy-route-server-rendering@1.0.0 start: `NODE_ENV=production webpack --progress && babel-node modules/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (B:\node\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (B:\node\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-router-lazy-route-server-rendering@1.0.0
11 verbose cwd B:\example-react-router-server-rendering-lazy-routes-master
12 error Windows_NT 10.0.10586
13 error argv "B:\node\node.exe" "B:\node\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error react-router-lazy-route-server-rendering@1.0.0 start: `NODE_ENV=production webpack --progress && babel-node modules/server.js`
17 error Exit status 1
18 error Failed at the react-router-lazy-route-server-rendering@1.0.0 start script 'NODE_ENV=production webpack --progress && babel-node modules/server.js'.
18 error This is most likely a problem with the react-router-lazy-route-server-rendering package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=production webpack --progress && babel-node modules/server.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-router-lazy-route-server-rendering
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-router-lazy-route-server-rendering
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by bhuvaneshCES** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-router-lazy-route-server-rendering@1.0.0
6 info start react-router-lazy-route-server-rendering@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-router-lazy-route-server-rendering@1.0.0 Failed to exec start script
9 verbose stack Error: react-router-lazy-route-server-rendering@1.0.0 start: `NODE_ENV=production webpack --progress && babel-node modules/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-router-lazy-route-server-rendering@1.0.0
11 verbose cwd F:\example-react-router-server-rendering-lazy-routes
12 error Windows_NT 6.1.7601
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error react-router-lazy-route-server-rendering@1.0.0 start: `NODE_ENV=production webpack --progress && babel-node modules/server.js`
17 error Exit status 1
18 error Failed at the react-router-lazy-route-server-rendering@1.0.0 start script 'NODE_ENV=production webpack --progress && babel-node modules/server.js'.
18 error This is most likely a problem with the react-router-lazy-route-server-rendering package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=production webpack --progress && babel-node modules/server.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-router-lazy-route-server-rendering
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-router-lazy-route-server-rendering
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
**Not able to start the project** Please it would be great if you could provide some **fix for this issue.**

**Comment by mdrulis-neurosys** [comment]
Solution: go to package.json and change the npm start script to: 
"webpack --progress && babel-node modules/server.js NODE_ENV=production"

**Comment by aalpgiray** [comment]
it is very old and I don't even remember this issue. Closing this due to inactivity.
